name: "Prepare Web Deploy"

on:
  push:
    branches: [main]
    paths: [web/**]    

permissions:
  contents: write

jobs:
  checkout-web-files-to-deploy-branch:
    name: "Checkout web files to deploy branch"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy web files to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web